# Use a Node.js image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the default development port
EXPOSE 3000

# Start the application using npm
CMD ["npm", "run", "start"]
