services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    command: >
      redis-server
      --requirepass "defaultdevpassword"
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --appendfsync everysec
      --maxmemory 100mb
      --maxmemory-policy noeviction
      --dir /data
      --loadmodule /opt/redis-stack/lib/redisearch.so
      --loadmodule /opt/redis-stack/lib/rejson.so
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a defaultdevpassword ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    
  api:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    container_name: express-api
    restart: always
    ports:
      - "3001:3001"
      - "3002:3002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - ./backend/.env

volumes:
  redis-data:
