version: "3.9"

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis-data:/data
      - ./backend/redis.prod.conf:/usr/local/etc/redis/redis.conf:ro
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: express-api
    restart: always
    ports:
      - "3001:3001"
      - "3002:3002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      NODE_ENV: production
      # Add any other required vars
      JWT_SECRET: ${JWT_SECRET}

volumes:
  redis-data:
