services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    command: >
      redis-server
      --requirepass "defaultdevpassword"
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --appendfsync everysec
      --maxmemory 100mb
      --maxmemory-policy noeviction
      --dir /data
      --loadmodule /opt/redis-stack/lib/redisearch.so
      --loadmodule /opt/redis-stack/lib/rejson.so
      --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a defaultdevpassword ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    
  api:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    container_name: express-api
    restart: always
    ports:
      - "3001:3001"
      - "3002:3002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - ./backend/.env

  postgres:
    image: postgres:latest
    container_name: postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: defaultdevpassword
      POSTGRES_DB: con4db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
      - ./backend/migrations/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      # - ./backend/migrations/game.nosql:/docker-entrypoint-initdb.d/2-dummy-data.sql # TODO add dummy data later
    restart: unless-stopped

volumes:
  redis-data:
  postgres-data: {}
