
export interface User {
  id: string;
  username: string | null;
  email: string | null;
  email_verified: boolean;
  created_at: string;
  updated_at: string;
  last_login: string | null;
  is_anonymous: boolean;

  // ??
  toSafeObject(): {
    id: string;
    username: string;
    email: string;
  };
}

export interface UserWithPassword extends User {
  // "PHC" format from Argon2, includes autogenerated salt
  password_hash: string;
}
