
export enum GameMode {
    
    STANDARD_BLITZ_RANKED = 1,
    STANDARD_BLITZ_CASUAL = 2,

    EVENT_GAMEMODES_TEMPLATE = 0xFFFF, // 65535
}

// const name = GameMode[id]; // "CLASSIC"
export enum GameState {
    ERRORED = -1,
    SCHEDULED = 1,
    IN_PROGRESS ,
    ABORTED,
    RED_WIN,
    YELLOW_WIN,
    AGREED_DRAW,
    RED_DISCONNECTED,
    YELLOW_DISCONNECTED,
    RED_RESIGNED,
    YELLOW_RESIGNED,
    RED_TIMEOUT,
    YELLOW_TIMEOUT,
}