import { z } from 'zod';

// Zod schema for User
export const UserSchema = z.object({
  id: z.string().uuid(),
  username: z.string(),
  email: z.string().email(),
  email_verified: z.boolean().nullable(),
  profile_pic: z.string().nullable(),
  password_hash: z.string().nullable(),
  mail_provider: z.string().length(1),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  last_login: z.string().datetime(),
});

export const RegistrationUserSchema = z.object({
  username: z.string().min(3).max(30).regex(/^[a-zA-Z0-9_.]*$/),
  email: z.string().email(),
  password: z.string().min(8).max(1024),
});

// Zod schema for User with password
export const UserWithPasswordSchema = UserSchema.extend({
  password_hash: z.string().min(1), // "PHC" format from Argon2, includes autogenerated salt
});

// TypeScript types derived from Zod schemas
export type User = z.infer<typeof UserSchema>;
export type UserWithPassword = z.infer<typeof UserWithPasswordSchema>;

