import { Tag } from './Tag';

export interface User {
  id: string;
  username: string;
  email: string;
  email_verified: boolean;
  created_at: string;
  updated_at: string;
  last_login: string | null;
  tags?: Tag[];

  // ??
  toSafeObject(): {
    id: string;
    username: string;
    email: string;
  };
}

export interface UserWithPassword extends User {
  // "PHC" format from Argon2, includes autogenerated salt
  password_hash: string;
}

`
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username STRING(30) UNIQUE NOT NULL,
  email STRING(320) UNIQUE NOT NULL,
  email_verified BOOLEAN NOT NULL DEFAULT false,
  password_hash STRING(1024) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login TIMESTAMP
);
`;