name: Docker Build Backend for DO

on:
  push:
    branches: [ "main", "testing-docker" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker backend image
      run: docker build . --file ./backend.dockerfile --tag backend:$(date +%s)


  build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
      - name: Build the Docker frontend image
        run: docker build . --file ./frontend.dockerfile --tag frontend:$(date +%s)
