name: deploy website

on:
  push:
    branches: [ "main", "DO-test" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+-website*'
  pull_request:
    branches: [ "main" ]

jobs:

  build-website-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag
        run: |
          if [[ $GITHUB_REF == refs/tags/*-staging ]]; then
            echo "TAG=nightly" >> "$GITHUB_ENV"
          else
            echo "TAG=latest" >> "$GITHUB_ENV"
          fi

      - name: Build and push
        run: |
          docker build -t ghcr.io/abhinav-gg/connectfour -f ./backend.dockerfile --target website .
          docker push ghcr.io/abhinav-gg/connectfour

  deploy-website:
    needs: build-website-image
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # These are the DigitalOcean App IDs for the production and staging environments
      - name: Set app
        run: |
          if [[ $GITHUB_REF == refs/tags/*-staging ]]; then
            echo "ID=staging??o.0" >> "$GITHUB_ENV"
          else
            echo "ID=3b794986-648d-4155-b596-45ada62b9a4e" >> "$GITHUB_ENV"
          fi

      - name: Deploy to DigitalOcean
        run: doctl apps create-deployment ${{ env.ID }}
